/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW.SalesInvoice;

import Controller.SalesInvoice.InvoiceSalesActionListener;
import Controller.SalesInvoice.SalesInvoiceTableListener;
import MODEL.SalesInvoice.SalesHeaderTable;
import MODEL.SalesInvoice.SalesInvoiceHeader;
import MODEL.SalesInvoice.SalesInvoiceLine;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;


/**
 *
 * @author Sarah
 */
public class BillFrame extends javax.swing.JFrame {

   

    /**
     * Creates new form BillFrame
     */
    public BillFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvoiceTable = new javax.swing.JTable();
        createnewinvoiceButton = new javax.swing.JButton();
        InvNumLBL = new javax.swing.JLabel();
        InvDateLBL = new javax.swing.JLabel();
        CustomerNameLBL = new javax.swing.JLabel();
        InvTotalLBL = new javax.swing.JLabel();
        invoiceNUMLbl = new javax.swing.JLabel();
        invoiceDateLbl = new javax.swing.JLabel();
        customerNameLbl = new javax.swing.JLabel();
        CustomerNameLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InvoiceItems = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        SalesInvoiceNumberField = new javax.swing.JTextField();
        SalesInvoiceDateField = new javax.swing.JTextField();
        SalesInvoiceCustomerNameField = new javax.swing.JTextField();
        SalesInvoiceTotalField = new javax.swing.JTextField();
        deleteInvoice = new javax.swing.JButton();
        InvoiceItem = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadMenuItem = new javax.swing.JMenuItem();
        SavedMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        InvoiceTable.getSelectionModel().addListSelectionListener(tableListener);
        jScrollPane1.setViewportView(InvoiceTable);

        createnewinvoiceButton.setText("Create NeW Invoice");
        createnewinvoiceButton.addActionListener(actionListener);
        createnewinvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createnewinvoiceButtonActionPerformed(evt);
            }
        });

        InvNumLBL.setText("INvoice Number ");

        InvDateLBL.setText("INvoice Date");

        CustomerNameLBL.setText("Customer Name");

        InvTotalLBL.setText("INvoice Total");

        InvoiceItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(InvoiceItems);

        saveButton.setText("SAVE");
        saveButton.addActionListener(actionListener);

        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(actionListener);

        SalesInvoiceNumberField.setText("SalesInvoiceNumber");

        SalesInvoiceDateField.setText("SalesInvoiceDate");

        SalesInvoiceCustomerNameField.setText("SalesInvoiceCustomerName");

        SalesInvoiceTotalField.setText("SalesInvoiceTotal");

        deleteInvoice.setText("deleteInvoice");
        deleteInvoice.addActionListener(actionListener);

        InvoiceItem.setText("invoice Items");

        jTextField1.setText("invoice Table");

        jMenu1.setText("File");

        LoadMenuItem.setText("LOAD Files");
        LoadMenuItem.addActionListener(actionListener);
        LoadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(LoadMenuItem);
        LoadMenuItem.getAccessibleContext().setAccessibleName("LOAD ");

        SavedMenuItem.setText("SAVED Files");
        SavedMenuItem.addActionListener(actionListener );
        SavedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavedMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(SavedMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(createnewinvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(218, 218, 218)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(229, 229, 229)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SalesInvoiceNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(SalesInvoiceDateField))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(InvNumLBL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(InvDateLBL))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SalesInvoiceCustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SalesInvoiceTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerNameLBL, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(InvTotalLBL, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerNameLbl)
                                    .addComponent(customerNameLbl)
                                    .addComponent(invoiceDateLbl)
                                    .addComponent(invoiceNUMLbl))))
                        .addGap(208, 208, 208))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(InvoiceItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvNumLBL)
                            .addComponent(invoiceNUMLbl)
                            .addComponent(SalesInvoiceNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(invoiceDateLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SalesInvoiceDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InvDateLBL))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(customerNameLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SalesInvoiceCustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CustomerNameLBL))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(CustomerNameLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SalesInvoiceTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InvTotalLBL))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InvoiceItem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createnewinvoiceButton)
                            .addComponent(deleteInvoice))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadMenuItemActionPerformed

    private void SavedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavedMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavedMenuItemActionPerformed

    private void createnewinvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createnewinvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createnewinvoiceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillFrame().setVisible(true);
            }
        });
    }
    
    
    public static SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    private SalesInvoiceTableListener  tableListener   = new SalesInvoiceTableListener(this);
    private InvoiceSalesActionListener actionListener = new InvoiceSalesActionListener(this);
    private ArrayList<SalesInvoiceHeader> invoicesArray;
    private ArrayList<SalesInvoiceLine> LinesArray;
    private SalesHeaderTable headerTablel;

    public void setHeadersArray(ArrayList<SalesInvoiceHeader> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }
    
        
    public SalesInvoiceHeader getInviceObject(int code) {
        for (SalesInvoiceHeader inv : invoicesArray) {
            if (inv.getNumber() == code) {
                return inv;
            }
        }
        return null;
    }
    
     public SalesHeaderTable getSalesHeaderTable() {
        return headerTablel;
    }

    public void setSalesHeaderTable(SalesHeaderTable headerTablel) {
        this.headerTablel = headerTablel;
    }

    public JTable getInvoiceItems() {
        return InvoiceItems;
    }

    public void setInvoiceItems(JTable InvoiceItems) {
        this.InvoiceItems = InvoiceItems;
    }

    public JTable getInvoiceTable() {
        return InvoiceTable;
    }

    public void setInvoiceTable(JTable InvoiceTable) {
        this.InvoiceTable = InvoiceTable;
    }

    public ArrayList<SalesInvoiceHeader> getInvoicesArray() {
        return invoicesArray;
    }

    public JLabel getCustomerNameLBL() {
        return CustomerNameLBL;
    }

//    public JLabel getCustomerNameLbl() {
//        return CustomerNameLbl;
//    }

    public JLabel getInvDateLBL() {
        return InvDateLBL;
    }

    public JLabel getInvNumLBL() {
        return InvNumLBL;
    }

    public JLabel getInvTotalLBL() {
        return InvTotalLBL;
    }

    public ArrayList<SalesInvoiceLine> getLinesArray() {
        return LinesArray;
    }

    public void setLinesArray(ArrayList<SalesInvoiceLine> LinesArray) {
        this.LinesArray = LinesArray;
    }


    
    
      public  ActionListener getActionListener() {
         return actionListener;

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerNameLBL;
    private javax.swing.JLabel CustomerNameLbl;
    private javax.swing.JLabel InvDateLBL;
    private javax.swing.JLabel InvNumLBL;
    private javax.swing.JLabel InvTotalLBL;
    private javax.swing.JTextField InvoiceItem;
    private javax.swing.JTable InvoiceItems;
    private javax.swing.JTable InvoiceTable;
    private javax.swing.JMenuItem LoadMenuItem;
    private javax.swing.JTextField SalesInvoiceCustomerNameField;
    private javax.swing.JTextField SalesInvoiceDateField;
    private javax.swing.JTextField SalesInvoiceNumberField;
    private javax.swing.JTextField SalesInvoiceTotalField;
    private javax.swing.JMenuItem SavedMenuItem;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createnewinvoiceButton;
    private javax.swing.JLabel customerNameLbl;
    private javax.swing.JButton deleteInvoice;
    private javax.swing.JLabel invoiceDateLbl;
    private javax.swing.JLabel invoiceNUMLbl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

//    private void setText(String file) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//
//    private static class deleteInvoice {
//
//        public deleteInvoice() {
//        }
//    }

 

 





}
